import{test}from'node:test';import assert from'node:assert/strict';
import{fork,execFileSync}from'node:child_process';import{mkdtempSync,readFileSync,writeFileSync,rmSync}from'node:fs';
import{join}from'node:path';import{tmpdir}from'node:os';import{fileURLToPath,pathToFileURL}from'node:url';import{performance}from'node:perf_hooks';
const workerSource=fileURLToPath(new URL('../server/review-real/projection-http-transport.ts',import.meta.url)),stub=fileURLToPath(new URL('./helpers/projection-http-stub.mjs',import.meta.url));
const SIZE=1185849,body={synthetic:'a'.repeat(SIZE-Buffer.byteLength(JSON.stringify({synthetic:''})))};
async function fixture(mode='fast',mutation:(s:string)=>string=s=>s){
 const child=fork(stub,[mode],{execPath:process.execPath,execArgv:['--experimental-transform-types'],detached:true,stdio:['ignore','pipe','pipe','ipc']});
 const messages:Array<Record<string,unknown>>=[];let stderr='';child.stderr!.on('data',b=>stderr+=b);child.on('message',m=>messages.push(m as Record<string,unknown>));
 const exited=new Promise<{code:number|null;signal:string|null}>(r=>child.once('exit',(code,signal)=>r({code,signal})));
 const until=Date.now()+8000;while(!messages.some(m=>m.event==='listening')){if(child.exitCode!==null)throw Error(stderr);if(Date.now()>until)throw Error('LISTEN_TIMEOUT');await new Promise(r=>setTimeout(r,10));}
 const port=Number(messages.find(m=>m.event==='listening')!.port),dir=mkdtempSync(join(tmpdir(),'projection-worker-test-')),path=join(dir,'transport.mts');
 const original=readFileSync(workerSource,'utf8');assert.equal(original.split('port: 3102,').length,2);writeFileSync(path,mutation(original.replace('port: 3102,',`port: ${port},`)),{mode:0o600});
 const module=await import(pathToFileURL(path).href);const request=(method:'POST'|'GET'='POST')=>module.requestProjectionJson({method,path:method==='POST'?'/internal/projections':'/internal/projections/receipts/op-snapshot-'+ 'a'.repeat(64),...(method==='POST'?{body}:{}),serviceIdentity:'synthetic-worker-test',timeoutMs:30000});
 const close=async()=>{if(child.exitCode===null&&child.signalCode===null&&child.connected)child.send('close',()=>{});await Promise.race([exited,new Promise(r=>setTimeout(r,2000))]);if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');const result=await exited;rmSync(dir,{recursive:true,force:true});assert.equal(result.code,0,stderr);const groups=execFileSync('/bin/ps',['-axo','pid=,pgid='],{encoding:'utf8'}).trim().split('\n').map(l=>l.trim().split(/\s+/).map(Number)).filter(r=>r[1]===child.pid);assert.deepEqual(groups,[]);};
 return {request,module,messages,close};
}
test('worker fully transfers the same 1,185,849 byte body and GET using original response rules',async()=>{const e=await fixture();try{const result=await e.request();assert.deepEqual(result,{kind:'response',status:200,body:{synthetic:true,received:true,characters:body.synthetic.length}});assert.equal((await e.request('GET')).status,200);}finally{await e.close();}});
test('parent event loop blocked forty seconds does not prevent independent worker body/response; reply arrives after exit',async()=>{const e=await fixture();try{const started=Date.now(),promise=e.request();const until=performance.now()+40000;while(performance.now()<until){}const result=await promise;assert.equal(result.kind,'response');assert.equal(result.status,200);const commit=e.messages.find(m=>m.event==='stub-commit');if(!commit)await new Promise(r=>setTimeout(r,30));assert.ok(Number(e.messages.find(m=>m.event==='stub-commit')!.at)-started<30000);assert.ok(Date.now()-started>=40000);}finally{await e.close();}});
test('worker retains the independent thirty second socket deadline; slow stub may commit after unknown',async()=>{const e=await fixture('slow');try{const start=performance.now(),result=await e.request();assert.deepEqual(result,{kind:'unknown'});const elapsed=performance.now()-start;assert.ok(elapsed>=29000&&elapsed<34000);const until=Date.now()+10000;while(!e.messages.some(m=>m.event==='stub-commit')&&Date.now()<until)await new Promise(r=>setTimeout(r,20));assert.ok(e.messages.some(m=>m.event==='stub-commit'));}finally{await e.close();}});
test('oversized response closes as unknown without retry',async()=>{const e=await fixture('large');try{assert.deepEqual(await e.request(),{kind:'unknown'});assert.equal(e.messages.filter(m=>m.event==='receive').length,1);}finally{await e.close();}});
test('untrusted method/path/headers/port/oversized body never reach stub',async()=>{const e=await fixture();try{const good={method:'POST',path:'/internal/projections',body,serviceIdentity:'synthetic-worker-test',timeoutMs:30000};for(const extra of [{method:'DELETE'},{path:'http://example.com/'},{port:3102},{serviceIdentity:'bad\r\nheader'},{timeoutMs:30001},{body:{synthetic:'a'.repeat(2*1024*1024)}}])assert.deepEqual(await e.module.requestProjectionJson({...good,...extra}),{kind:'unknown'});assert.equal(e.messages.filter(m=>m.event==='receive').length,0);}finally{await e.close();}});

test('worker crash and invalid/duplicate reply settle unknown without an HTTP attempt or retry',async()=>{for(const replacement of ['throw new Error("synthetic worker crash");','parentPort.postMessage({kind:"invalid"});parentPort.close();','parentPort.postMessage({kind:"unknown"});parentPort.postMessage({kind:"unknown"});parentPort.close();']){const e=await fixture('fast',s=>s.replace('const result=await requestJson(workerData);\n parentPort.postMessage(result);\n parentPort.close();',replacement));try{assert.deepEqual(await e.request(),{kind:'unknown'});assert.equal(e.messages.filter(m=>m.event==='receive').length,0);}finally{await e.close();}}});
test('independent resource guards close silent alive, valid-message alive and synchronously stuck workers',async()=>{
 for(const replacement of ['setInterval(()=>{},1000);','parentPort.postMessage({kind:"response",status:200,body:{}});setInterval(()=>{},1000);','while(true){}']){
  const e=await fixture('fast',s=>s.replace('WORKER_RESOURCE_DEADLINE_MS=45_000','WORKER_RESOURCE_DEADLINE_MS=100').replace('PARENT_RESOURCE_DEADLINE_MS=60_000','PARENT_RESOURCE_DEADLINE_MS=250').replace('const result=await requestJson(workerData);\n parentPort.postMessage(result);\n parentPort.close();',replacement));
  try{const start=performance.now();assert.deepEqual(await e.request(),{kind:'unknown'});assert.ok(performance.now()-start<3000);assert.equal(e.messages.filter(m=>m.event==='receive').length,0);}finally{await e.close();}
 }
});
