import {createHash,createPrivateKey,generateKeyPairSync} from "node:crypto";
import {chmodSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,test} from "vitest";
import {canonicalJson} from "../server/db/profile.ts";
import {buildProjectionSnapshot,buildProjectionTaskEnvelope,buildPublicProjectionRecord,buildReviewBundleMaterial,buildXPageReviewBundleMaterial,
  derivePublicId,deriveXPagePublicId,verifyStoredPublicProjection,verifyStoredReviewBundle} from "../server/review-real/mapping.ts";
import {PublicProjectionRecordSchema,ReviewBundlePublicPayloadSchema} from "../server/review-real/schema.ts";
import {ProjectionReceiver,signProjectionTaskEnvelope} from "../server/review-real/projection.ts";
import {PublicRealSnapshotReader} from "../server/public/snapshot-adapter.ts";
import {handlePublicFeed,handlePublicStory} from "../server/public/http.ts";
import {verifyTrustedXCapture,type TrustedXCapture} from "../server/x-page/trusted-capture.ts";
import {testXProducer,testHash,TEST_X_NOW} from "./helpers/x-page-trusted.ts";

// These two RSS vectors were generated from the pre-C mapping/schema restored
// and hash-checked against the predirty manifest, including a fixed synthetic
// signing key. Neither vector was generated by the implementation under test.
const golden=JSON.parse(readFileSync(new URL("./helpers/x-page-rss-golden.json",import.meta.url),"utf8")) as {
  syntheticSigningSeedHex:string;vectors:Array<{name:string;input:Parameters<typeof buildReviewBundleMaterial>[0];bundle:ReturnType<typeof buildReviewBundleMaterial>;
    publicId:string;projectionJson:string;projectionHash:string;envelopeJson:string;envelopeHash:string;signedJson:string;signedSha256:string}>;
};
const cleanups:Array<()=>void>=[];
afterEach(()=>{for(const cleanup of cleanups.splice(0).reverse())cleanup();});
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
function xBundle(change?:(capture:TrustedXCapture)=>TrustedXCapture) {
  const producer=testXProducer(),raw=producer.capture({text:"Complete visible original post. "+"原帖完整正文。".repeat(700)});
  const capture=verifyTrustedXCapture({capture:change?producer.resign(change(raw)):raw,trust:producer.trust,now:new Date(TEST_X_NOW)});
  const target={candidateId:`xpage-${capture.normalized.identity}`,sourceRevision:2,inputContentHash:capture.normalized.sourceVersionHash};
  const input={bundleId:"synthetic-x-bundle",bundleRevision:1,createdAt:TEST_X_NOW,target,capture,
    editable:{titleZh:"原帖作者分享比赛观察",summaryZh:"仅根据已捕获完整原帖整理的中文摘要。",notes:"private-editor-note"}};
  const bundle=buildXPageReviewBundleMaterial(input);
  const publicId=deriveXPagePublicId(target.candidateId,bundle.bundleHash);
  const projection=buildPublicProjectionRecord({publicId,bundleHash:bundle.bundleHash,publishedAt:TEST_X_NOW,publicPayload:bundle.publicPayload,keyPointsZh:["原帖作者的比赛观察"]});
  return {producer,capture,target,input,bundle,publicId,projection};
}

describe("X Public payload branch and unchanged RSS canonical signatures",()=>{
  test.each(golden.vectors)("preserves all predirty RSS $name bytes and signature",vector=>{
    const bundle=buildReviewBundleMaterial(vector.input);expect(bundle).toEqual(vector.bundle);
    const publicId=derivePublicId(vector.input.candidate.candidateId,bundle.bundleHash);expect(publicId).toBe(vector.publicId);
    const projection=buildPublicProjectionRecord({publicId,bundleHash:bundle.bundleHash,publishedAt:"2026-09-07T00:02:00.000Z",publicPayload:bundle.publicPayload,keyPointsZh:["既有要点"]});
    expect(canonicalJson(projection)).toBe(vector.projectionJson);expect(projection.projectionHash).toBe(vector.projectionHash);
    const snapshot=buildProjectionSnapshot({snapshotGeneration:1,previousSnapshotManifestHash:null,records:[projection]});
    const envelope=buildProjectionTaskEnvelope({deliveryId:`op-snapshot-${snapshot.snapshotManifestHash}`,idempotencyKey:`snapshot-sync:0:${snapshot.snapshotManifestHash}`,
      reconcileKey:`reconcile:snapshot:${snapshot.snapshotManifestHash}`,snapshot,attempt:0,createdAt:"2026-09-07T00:02:00.000Z",deadlineAt:"2026-09-07T00:17:00.000Z"});
    expect(envelope.envelopeJson).toBe(vector.envelopeJson);expect(envelope.envelopeHash).toBe(vector.envelopeHash);
    const privateKey=createPrivateKey({key:Buffer.from(`302e020100300506032b657004220420${golden.syntheticSigningSeedHex}`,"hex"),format:"der",type:"pkcs8"});
    const signed=signProjectionTaskEnvelope({...envelope,signingKeyId:"synthetic-golden-key",privateKey});
    expect(canonicalJson(signed)).toBe(vector.signedJson);expect(hash(canonicalJson(signed))).toBe(vector.signedSha256);
  });
  test("commits the full capture in the private bundle and omits private evidence from Public",()=>{
    const env=xBundle();expect(env.bundle.publicPayload.sourceTitle.length).toBeGreaterThan(1000);
    expect(env.bundle.publicPayload.sourceTitle).toBe(env.capture.normalized.text);
    expect(env.projection).toMatchObject({publicId:expect.stringMatching(/^public-x-[0-9a-f]{64}$/),contentType:"driver_social",state:"media_missing",media:null,
      source:{sourceId:"x_f1",platform:"x",displayName:"F1",byline:"F1 (@f1)"},originalLink:{enabled:true,url:env.capture.normalized.canonicalUrl}});
    expect(verifyStoredReviewBundle({...env.bundle,bundleId:env.input.bundleId,bundleRevision:env.input.bundleRevision,createdAt:env.input.createdAt})).toEqual(env.bundle);
    expect(verifyStoredPublicProjection(canonicalJson(env.projection),env.projection.projectionHash)).toEqual(env.projection);
    for(const secret of ["xCaptureSha256","candidateId","sourcePayloadHash","toolReceiptSha256","captureArtifactSha256","producerId","receiptId","sourceTitle","private-editor-note",env.capture.captureSha256])expect(canonicalJson(env.projection)).not.toContain(secret);
  });
  test("binds an edit beyond the candidate preview to a different bundle and public identity",()=>{
    const first=xBundle(),second=xBundle(raw=>({...raw,post:{...raw.post,text:raw.post.text+" Late full-text correction."}}));
    expect(second.capture.normalized.sourceVersionHash).not.toBe(first.capture.normalized.sourceVersionHash);
    expect(second.bundle.bundleHash).not.toBe(first.bundle.bundleHash);expect(second.publicId).not.toBe(first.publicId);
    expect(()=>buildXPageReviewBundleMaterial({...second.input,target:first.target})).toThrow("REVIEW_DATA_INVALID");
  });
  test("never turns captured social media references into published media",()=>{
    const env=xBundle(raw=>({...raw,post:{...raw.post,media:[{kind:"image",url:"https://pbs.twimg.com/media/synthetic.jpg",altText:"Captured reference only"}]}}));
    expect(env.capture.normalized.mediaReferences).toHaveLength(1);expect(env.bundle.publicPayload.media).toEqual([]);expect(env.projection.media).toBeNull();
  });
  test("keeps original author attribution for quotes, replies and reposts",()=>{
    const env=xBundle(raw=>({...raw,post:{...raw.post,observedOnHandle:"mclarenf1",pageUrl:"https://x.com/mclarenf1",
      relations:{repostedByHandle:"mclarenf1",quotedStatusUrl:"https://x.com/fia/status/1000000000000000000",replyToStatusUrl:"https://x.com/mclarenf1/status/1000000000000000001"}},
      evidence:{...raw.evidence,pageUrl:"https://x.com/mclarenf1",observedSourceId:"x_mclarenf1",observedSourceIdentitySha256:testHash("mclarenf1")}}));
    expect(env.projection.source.byline).toBe("F1 (@f1)");expect(env.projection.source.sourceId).toBe("x_f1");
    expect(env.projection.detail.bodyZh).toHaveLength(2);
    expect(env.projection.detail.bodyZh[1]).toContain("原帖作者为 @f1，由 @mclarenf1 转帖");
    expect(env.projection.detail.bodyZh[1]).toContain("原帖引用了另一条帖子");
    expect(env.projection.detail.bodyZh[1]).toContain("原帖是对以下帖子的回复");
    expect(env.projection.originalLink.url).toBe(env.capture.normalized.canonicalUrl);
  });
  test.each([
    ["rss source",{sourceId:"motorsport-f1-news"}], ["unselected X",{sourceId:"x_unknown"}],
    ["wrong platform",{sourcePlatform:"rss"}], ["wrong content type",{contentType:"race_news"}],
    ["wrong byline",{sourceAuthor:"McLaren (@mclarenf1)"}], ["wrong author",{authorHandle:"mclarenf1"}],
    ["wrong URL author",{canonicalUrl:"https://x.com/mclarenf1/status/1000000000000000000"}],
    ["non-X URL",{canonicalUrl:"https://example.com/f1/status/nope"}],
    ["query URL",{canonicalUrl:"https://x.com/f1/status/1000000000000000000?s=20"}],
    ["invalid status",{canonicalUrl:"https://x.com/f1/status/nope"}],
    ["noncanonical platform casing",{canonicalUrl:"https://X.com/f1/status/1000000000000000000"}],
    ["impossible timestamp",{sourcePublishedAt:"2025-01-01T00:00:00.000Z"}],
    ["unsafe summary",{summaryZh:"正文\u202e隐藏控制符"}],
    ["raw internal field",{toolReceiptSha256:"a".repeat(64)}],
  ])("rejects malformed X private payload: %s",(_name,change)=>{
    expect(ReviewBundlePublicPayloadSchema.safeParse({...xBundle().bundle.publicPayload,...change}).success).toBe(false);
  });
  test("the strict X Public branch refuses private fields, RSS prefixes and media",()=>{
    const {projection}=xBundle();
    for(const change of [{publicId:`public-rss-${"a".repeat(64)}`},{xCaptureSha256:"a".repeat(64)},{media:{kind:"source_image",assetRef:"https://pbs.twimg.com/media/unsafe.jpg"}},{source:{...projection.source,platform:"rss"}}])expect(PublicProjectionRecordSchema.safeParse({...projection,...change}).success).toBe(false);
  });
  test("mixed signed RSS/X snapshot is received and served by existing Public feed and detail",async()=>{
    const env=xBundle(),root=mkdtempSync(join(realpathSync(tmpdir()),"x-public-payload-test-"));chmodSync(root,0o700);cleanups.push(()=>rmSync(root,{recursive:true,force:true}));
    const keys=generateKeyPairSync("ed25519"),keyPath=join(root,"public.pem");writeFileSync(keyPath,keys.publicKey.export({format:"pem",type:"spki"}),{mode:0o600});
    const rss=JSON.parse(golden.vectors[0].projectionJson),snapshot=buildProjectionSnapshot({snapshotGeneration:1,previousSnapshotManifestHash:null,records:[rss,env.projection]});
    const envelope=buildProjectionTaskEnvelope({deliveryId:`op-snapshot-${snapshot.snapshotManifestHash}`,idempotencyKey:`snapshot-sync:0:${snapshot.snapshotManifestHash}`,
      reconcileKey:`reconcile:snapshot:${snapshot.snapshotManifestHash}`,snapshot,attempt:0,createdAt:TEST_X_NOW,deadlineAt:"2026-09-07T00:15:00.000Z"});
    const receiver=new ProjectionReceiver({root:join(root,"projection"),signingKeyId:"synthetic-public-key",publicKey:keys.publicKey,now:()=>Date.parse(TEST_X_NOW)});
    const received=receiver.receive(signProjectionTaskEnvelope({...envelope,signingKeyId:"synthetic-public-key",privateKey:keys.privateKey}));
    expect(received.activeSnapshotGeneration).toBe(1);
    const reader=new PublicRealSnapshotReader({projectionRoot:join(root,"projection"),signingKeyId:"synthetic-public-key",verifyKeyPath:keyPath});
    const feed=handlePublicFeed(new Request("https://synthetic.invalid/api/public/feed?source=x_f1&contentType=driver_social"),reader);expect(feed.status).toBe(200);
    const json=await feed.json();expect(json.items).toHaveLength(1);expect(json.items[0].source.byline).toBe("F1 (@f1)");
    const detail=handlePublicStory(env.publicId,reader);expect(detail.status).toBe(200);expect((await detail.json()).story.publicId).toBe(env.publicId);
    expect(canonicalJson(reader.getFeed({source:null,contentType:null,cursor:null}))).not.toContain("captureSha256");
    expect(handlePublicFeed(new Request("https://synthetic.invalid/api/public/feed?source=x_unselected"),reader).status).toBe(400);
    expect(reader.getDetail(rss.publicId)).toMatchObject({story:{source:{platform:"rss"}}});
  });
});
